### ISSUE TITLE
Scaling of environments needs to be updated

### ISSUE THREAD

**Issue by Bagaboo** [collector-bank/savings-template#17]
The readme-file in the Savings code base has been updated with the correct scale of the machines for all environments. We need to go through the settings in Azure and make sure it is correct. Also, we need to update the scripts to reflect the scaling requirements.

**Comment by perjahn** [comment]
1. To minimize the maintenance of syncing documentation, the template+parameter files should be used as the actual source of how the environments should be setup. Though the readme file could of course include some reference to the parameter files.
2. I guess this issue is really about making the sizes in the arm templates configurable and putting size configuration in the parameter files.

**Comment by Bagaboo** [comment]
Excellent. Let's make it configurable.

**Comment by perjahn** [comment]
https://github.com/collector-bank/savings-template/pull/20/commits/cb03e302734c18c103b822b7667f96bad600a00e

**Comment by perjahn** [comment]
Sizes are now configurable for everything.

**Comment by perjahn** [comment]
done.
